---
- name: Download activiti
  stat: path=/vagrant/activiti-{{ activiti_version }}.zip
  register: activiti_zip_archive

- get_url:
    url: https://github.com/Activiti/Activiti/releases/download/activiti-{{ activiti_version }}/activiti-{{ activiti_version }}.zip
    dest: /vagrant
    validate_certs: false
    timeout: 60
  when: (not activiti_zip_archive.stat.exists)

- name: Expand activiti zip
  unarchive:
    src=/vagrant/activiti-{{ activiti_version }}.zip
    dest=/tmp
    copy=no

- name: Create target directory
  file: path=/opt/activiti-{{ activiti_version }}/activiti-{{ item }} state=directory mode=0755
  with_items:
    - rest
    - app
    - admin

- name: Expand war
  unarchive:
    src=/tmp/activiti-{{ activiti_version }}/wars/activiti-{{ item }}.war
    dest=/opt/activiti-{{ activiti_version }}/activiti-{{ item }}
    copy=no
  with_items:
    - rest
    - app
    - admin

- name: activiti-app.properties (activiti-app)
  template:
    src=activiti-app.properties
    dest=/opt/activiti-6.0.0/activiti-app/WEB-INF/classes/META-INF/activiti-app/activiti-app.properties
    force=yes

- name: db.properties (activiti-rest)
  template:
    src=db.properties
    dest=/opt/activiti-6.0.0/activiti-rest/WEB-INF/classes/db.properties
    force=yes

- name: engine.properties (activiti-rest)
  template:
    src=engine.properties
    dest=/opt/activiti-6.0.0/activiti-rest/WEB-INF/classes/engine.properties
    force=yes

- name: activiti-admin.properties (activiti-admin)
  template:
    src=activiti-admin.properties
    dest=/opt/activiti-6.0.0/activiti-admin/WEB-INF/classes/META-INF/activiti-admin/activiti-admin.properties
    force=yes

- name: deploy activiti
  command:
    /opt/glassfish4/bin/asadmin deploy --force true --type war /opt/activiti-6.0.0/activiti-{{ item }}
  with_items:
    - rest
    - app
    - admin
