---
- name: Download activiti
  stat: path=/vagrant/activiti-{{ activiti_version }}.zip
  register: activiti_zip_archive

- get_url:
    url: https://github.com/Activiti/Activiti/releases/download/activiti-{{ activiti_version }}/activiti-{{ activiti_version }}.zip
    dest: /vagrant
    validate_certs: false
    timeout: 60
  when: (not activiti_zip_archive.stat.exists)

- name: Expand activiti zip
  unarchive:
    src=/vagrant/activiti-{{ activiti_version }}.zip
    dest=/tmp
    copy=no

- name: Create target directory
  file: path=/opt/activiti-{{ activiti_version }}/activiti-{{ item }} state=directory mode=0755
  with_items:
    - rest
    - app
    - admin

- name: Expand war
  unarchive:
    src=/tmp/activiti-{{ activiti_version }}/wars/activiti-{{ item }}.war
    dest=/opt/activiti-{{ activiti_version }}/activiti-{{ item }}
    copy=no
  with_items:
    - rest
    - app
    - admin
