---
- name: JavaEE
  hosts: jee
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - ../ansible_common/common
    - { role: ../ansible_common/postgres
        , db_name: sampledb
        , db_passwd: "{{ sampledb_passwd }}" }
    - { role: ../ansible_common/glassfish
        , db_name: sampledb
        , db_passwd: "{{ sampledb_passwd }}"
        , db: postgresql
      }
    - { role: ../ansible_common/firewalld, PORTS:["4848/tcp","8080/tcp","5432/tcp"] }
