---
- name: JavaEE
  hosts: jee
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - ../ansible_common/common
    - ../ansible_common/glassfish
    - { role: ../ansible_common/firewalld, PORTS:["4848/tcp","8080/tcp"] }
